version: '3.8'

services:
  web:
    image: stracommglobal-web
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stracommglobal-web
    restart: always
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=production
